import {
  DEFAULT_LANGUAGE,
  OG_LOCALE_MAP,
  SUPPORTED_LANGUAGES,
  isRtl,
  resolveLanguage,
} from '../utils/language-config';

export const BASE_URL = 'https://getmaca.de';

export const SEO_PAGE_SLUGS = [
  'faq',
  'guide',
  'troubleshooting',
  'privacy',
  'terms',
  'imprint',
  'feedback',
] as const;

export type SeoPageKey = 'home' | typeof SEO_PAGE_SLUGS[number];

const PAGE_TITLES: Record<SeoPageKey, Record<string, string>> = {
  home: {
    en: 'MACA – Per-App Volume Control for macOS | Mixer, EQ & Profiles',
    de: 'MACA – Lautstärke pro App für macOS | Mixer, EQ & Profile',
    fr: 'MACA – Volume par Application macOS | Mixer, EQ & Profils Audio',
    es: 'MACA – Volumen por App en macOS | Mezclador, EQ y Perfiles',
    it: 'MACA – Volume per App su macOS | Mixer, EQ e Profili Audio',
    ja: 'MACA – macOSアプリ別音量コントロール | ミキサー・EQ・プロファイル',
    'zh-Hans': 'MACA – macOS每应用音量控制 | 混音器、EQ与音频配置',
    'zh-Hant': 'MACA – macOS每應用音量控制 | 混音器、EQ與音頻配置',
    ar: 'MACA – تحكم صوت لكل تطبيق على macOS | خلاط ومعادل وملفات صوتية',
    ru: 'MACA – Громкость каждого приложения на macOS | Микшер, EQ и профили',
    nl: 'MACA – Volume per app voor macOS | Mixer, EQ & Profielen',
    tr: 'MACA – macOS uygulama başına ses | Mikser, EQ ve Profiller',
    sv: 'MACA – Volym per app för macOS | Mixer, EQ & Ljudprofiler',
    da: 'MACA – Lydstyrke per app for macOS | Mixer, EQ & Lydprofiler',
    ko: 'MACA – macOS 앱별 볼륨 컨트롤 | 믹서, EQ & 프로필',
    nb: 'MACA – Volum per app for macOS | Mikser, EQ & Lydprofiler',
  },
  faq: {
    en: 'FAQ – MACA Master Audio Control for macOS',
    de: 'FAQ – MACA Master Audio Control für macOS',
    fr: 'FAQ – MACA Contrôle Audio pour macOS',
    es: 'FAQ – MACA Control de Audio para macOS',
    it: 'FAQ – MACA Controllo Audio per macOS',
    ja: 'よくある質問 – MACA Master Audio Control',
    'zh-Hans': '常见问题 – MACA Master Audio Control',
    'zh-Hant': '常見問題 – MACA Master Audio Control',
    ar: 'أسئلة متكررة – MACA تحكم الصوت الرئيسي لـ macOS',
    ru: 'Часто задаваемые вопросы – MACA Управление громкостью для macOS',
    nl: 'FAQ – MACA Master Audio Control voor macOS',
    tr: 'SSS – MACA Master Audio Control için macOS',
    sv: 'FAQ – MACA Master Audio Control för macOS',
    da: 'FAQ – MACA Master Audio Control for macOS',
    ko: 'FAQ – MACA Master Audio Control for macOS',
    nb: 'FAQ – MACA Master Audio Control for macOS',
  },
  guide: {
    en: 'Setup Guide – MACA Per-App Volume, EQ & Profiles for macOS',
    de: 'Einrichtung – MACA Lautstärke pro App, EQ & Profile für macOS',
    fr: 'Guide de Configuration – MACA Volume par App, EQ & Profils macOS',
    es: 'Guía de Configuración – MACA Volumen por App, EQ y Perfiles macOS',
    it: 'Guida alla Configurazione – MACA Volume per App, EQ e Profili macOS',
    ja: 'セットアップガイド – MACA アプリ別音量・EQ・プロファイル設定',
    'zh-Hans': '设置指南 – MACA 每应用音量、EQ与配置文件设置',
    'zh-Hant': '設定指南 – MACA 每應用音量、EQ與配置文件設定',
    ar: 'دليل الإعداد – MACA صوت كل تطبيق والمعادل والملفات الصوتية',
    ru: 'Руководство по настройке – MACA Громкость, EQ и профили для macOS',
    nl: 'Installatiegids – MACA Volume per App, EQ & Profielen voor macOS',
    tr: 'Kurulum Rehberi – MACA Uygulama Sesi, EQ ve Profiller macOS',
    sv: 'Installationsguide – MACA Volym per App, EQ & Profiler för macOS',
    da: 'Opsætningsguide – MACA Lydstyrke per App, EQ & Profiler for macOS',
    ko: '설정 가이드 – MACA 앱별 볼륨, EQ & 프로필 macOS',
    nb: 'Oppsettguide – MACA Volum per App, EQ & Profiler for macOS',
  },
  troubleshooting: {
    en: 'Troubleshooting – Fix MACA Audio Issues on macOS',
    de: 'Fehlerbehebung – MACA Audio-Probleme auf macOS lösen',
    fr: 'Dépannage – Résoudre les Problèmes Audio MACA sur macOS',
    es: 'Solución de Problemas – Resolver Problemas de Audio MACA en macOS',
    it: 'Risoluzione Problemi – Risolvere Problemi Audio MACA su macOS',
    ja: 'トラブルシューティング – MACA macOS音声問題の解決',
    'zh-Hans': '故障排除 – 解决MACA macOS音频问题',
    'zh-Hant': '故障排除 – 解決MACA macOS音頻問題',
    ar: 'استكشاف الأخطاء – حل مشاكل صوت MACA على macOS',
    ru: 'Устранение неполадок – Решение проблем со звуком MACA на macOS',
    nl: 'Probleemoplossing – MACA Audioproblemen Oplossen op macOS',
    tr: 'Sorun Giderme – MACA macOS Ses Sorunlarını Çözme',
    sv: 'Felsökning – Lös MACA Ljudproblem på macOS',
    da: 'Fejlfinding – Løs MACA Lydproblemer på macOS',
    ko: '문제 해결 – MACA macOS 오디오 문제 수정',
    nb: 'Feilsøking – Løs MACA Lydproblemer på macOS',
  },
  privacy: {
    en: 'Privacy Policy – MACA Master Audio Control',
    de: 'Datenschutzerklärung – MACA Master Audio Control',
    fr: 'Politique de Confidentialité – MACA Master Audio Control',
    es: 'Política de Privacidad – MACA Master Audio Control',
    it: 'Informativa sulla Privacy – MACA Master Audio Control',
    ja: 'プライバシーポリシー – MACA Master Audio Control',
    'zh-Hans': '隐私政策 – MACA Master Audio Control',
    'zh-Hant': '隱私政策 – MACA Master Audio Control',
    ar: 'سياسة الخصوصية – MACA تحكم الصوت الرئيسي لـ macOS',
    ru: 'Политика конфиденциальности – MACA Управление громкостью для macOS',
    nl: 'Privacybeleid – MACA Master Audio Control voor macOS',
    tr: 'Gizlilik Politikası – MACA Master Audio Control',
    sv: 'Integritetspolicy – MACA Master Audio Control',
    da: 'Privatlivspolitik – MACA Master Audio Control',
    ko: '개인 정보 보호 정책 – MACA Master Audio Control',
    nb: 'Personvern – MACA Master Audio Control',
  },
  terms: {
    en: 'Terms of Use – MACA Master Audio Control',
    de: 'Nutzungsbedingungen – MACA Master Audio Control',
    fr: "Conditions d'Utilisation – MACA Master Audio Control",
    es: 'Términos de Uso – MACA Master Audio Control',
    it: "Termini d'Uso – MACA Master Audio Control",
    ja: '利用規約 – MACA Master Audio Control',
    'zh-Hans': '使用条款 – MACA Master Audio Control',
    'zh-Hant': '使用條款 – MACA Master Audio Control',
    ar: 'شروط الاستخدام – MACA تحكم الصوت الرئيسي لـ macOS',
    ru: 'Условия использования – MACA Управление громкостью для macOS',
    nl: 'Gebruiksvoorwaarden – MACA Master Audio Control voor macOS',
    tr: 'Kullanım Şartları – MACA Master Audio Control',
    sv: 'Användarvillkor – MACA Master Audio Control',
    da: 'Brugervilkår – MACA Master Audio Control',
    ko: '이용 약관 – MACA Master Audio Control',
    nb: 'Vilkår for bruk – MACA Master Audio Control',
  },
  imprint: {
    en: 'Imprint – MACA Master Audio Control',
    de: 'Impressum – MACA Master Audio Control',
    fr: 'Mentions Légales – MACA Master Audio Control',
    es: 'Aviso Legal – MACA Master Audio Control',
    it: 'Note Legali – MACA Master Audio Control',
    ja: '法的情報 – MACA Master Audio Control',
    'zh-Hans': '法律信息 – MACA Master Audio Control',
    'zh-Hant': '法律資訊 – MACA Master Audio Control',
    ar: 'البيان القانوني – MACA تحكم الصوت الرئيسي لـ macOS',
    ru: 'Юридическая информация – MACA Управление громкостью для macOS',
    nl: 'Colofon – MACA Master Audio Control',
    tr: 'Yasal Bilgiler – MACA Master Audio Control',
    sv: 'Impressum – MACA Master Audio Control',
    da: 'Impressum – MACA Master Audio Control',
    ko: '법적 정보 – MACA Master Audio Control',
    nb: 'Impressum – MACA Master Audio Control',
  },
  feedback: {
    en: 'Feedback – MACA Master Audio Control',
    de: 'Feedback – MACA Master Audio Control',
    fr: "Retour d'expérience – MACA Master Audio Control",
    es: 'Comentarios – MACA Master Audio Control',
    it: 'Feedback – MACA Master Audio Control',
    ja: 'フィードバック – MACA Master Audio Control',
    'zh-Hans': '反馈 – MACA Master Audio Control',
    'zh-Hant': '反饋 – MACA Master Audio Control',
    ar: 'التعليقات – MACA تحكم الصوت الرئيسي لـ macOS',
    ru: 'Отзывы – MACA Управление громкостью для macOS',
    nl: 'Feedback – MACA Master Audio Control voor macOS',
    tr: 'Geri Bildirim – MACA Master Audio Control',
    sv: 'Feedback – MACA Master Audio Control',
    da: 'Feedback – MACA Master Audio Control',
    ko: '피드백 – MACA Master Audio Control',
    nb: 'Tilbakemelding – MACA Master Audio Control',
  },
};

const META_DESCRIPTIONS: Record<SeoPageKey, Record<string, string>> = {
  home: {
    en: 'MACA – Per-app volume control for macOS. Individual mixer, 10-band EQ, audio profiles, Focus Mode. No data collection. One-time purchase. Free version available.',
    de: 'MACA – Lautstärke pro App für macOS. Individueller Mixer, 10-Band-EQ, Audio-Profile, Fokus-Modus. Keine Daten. Einmaliger Kauf. Kostenlose Version verfügbar.',
    fr: 'MACA – Volume par application sur macOS. Mixer individuel, EQ 10 bandes, profils audio, Mode Focus. Aucune donnée. Achat unique. Version gratuite disponible.',
    es: 'MACA – Volumen por app en macOS. Mezclador individual, EQ 10 bandas, perfiles de audio, Modo Enfoque. Sin datos. Compra única. Versión gratuita disponible.',
    it: 'MACA – Volume per app su macOS. Mixer individuale, EQ 10 bande, profili audio, Modalità Focus. Nessun dato. Acquisto unico. Versione gratuita disponibile.',
    ja: 'MACA – macOSのアプリごとの音量コントロール。個別ミキサー、10バンドEQ、オーディオプロファイル、フォーカスモード。データ収集なし。買い切り。無料版あり。',
    'zh-Hans': 'MACA – macOS每应用音量控制。独立混音器、10段EQ、音频配置文件、专注模式。无数据收集。一次性购买。提供免费版本。',
    'zh-Hant': 'MACA – macOS每應用音量控制。獨立混音器、10段EQ、音頻配置文件、專注模式。無數據收集。一次性購買。提供免費版本。',
    ar: 'MACA – تحكم في مستوى الصوت لكل تطبيق على macOS. خلاط فردي، معادل صوت 10 نطاقات، ملفات صوتية، وضع التركيز. بدون جمع بيانات. شراء لمرة واحدة. إصدار مجاني متاح.',
    ru: 'MACA – Управление громкостью каждого приложения на macOS. Индивидуальный микшер, 10-полосный эквалайзер, аудиопрофили, режим фокусировки. Без сбора данных. Разовая покупка. Бесплатная версия.',
    nl: 'MACA – Volume per app voor macOS. Individuele mixer, 10-bands EQ, audioprofielen, Focusmodus. Geen gegevensverzameling. Eenmalige aankoop. Gratis versie beschikbaar.',
    tr: 'MACA – macOS için uygulama başına ses kontrolü. Bireysel mikser, 10 bantlı EQ, ses profilleri, Odak Modu. Veri toplama yok. Tek seferlik satın alma. Ücretsiz sürüm mevcut.',
    sv: 'MACA – Volymkontroll per app för macOS. Individuell mixer, 10-bands EQ, ljudprofiler, Fokusläge. Ingen datainsamling. Engångsköp. Gratisversion tillgänglig.',
    da: 'MACA – Per-app lydstyrkekontrol for macOS. Individuel mixer, 10-bands EQ, lydprofiler, Fokusmodus. Ingen datainsamling. Én gangskøb. Gratis version tilgængelig.',
    ko: 'MACA – macOS 앱별 볼륨 컨트롤. 개별 믹서, 10대 EQ, 오디오 프로필, 포커스 모드. 데이터 수집 없음. 일회 구매. 무료 버전 제공.',
    nb: 'MACA – Per-app volumkontroll for macOS. Individuell mixer, 10-bands EQ, lydprofiler, Fokusmodus. Ingen datainsamling. Én gangskjøp. Gratis versjon tilgjengelig.',
  },
  faq: {
    en: 'Frequently asked questions about MACA – per-app volume control for macOS. Setup, features, pricing, compatibility and troubleshooting answered.',
    de: 'Häufig gestellte Fragen zu MACA – Lautstärke pro App für macOS. Einrichtung, Funktionen, Preise, Kompatibilität und Fehlerbehebung beantwortet.',
    fr: 'Questions fréquentes sur MACA – volume par application pour macOS. Installation, fonctionnalités, tarifs, compatibilité et dépannage.',
    es: 'Preguntas frecuentes sobre MACA – volumen por app para macOS. Instalación, funciones, precios, compatibilidad y solución de problemas.',
    it: 'Domande frequenti su MACA – volume per app su macOS. Configurazione, funzionalità, prezzi, compatibilità e risoluzione problemi.',
    ja: 'MACA（macOSアプリ別音量コントロール）のよくある質問。セットアップ、機能、料金、互換性、トラブルシューティング。',
    'zh-Hans': 'MACA常见问题 – macOS每应用音量控制。安装、功能、价格、兼容性和故障排除。',
    'zh-Hant': 'MACA常見問題 – macOS每應用音量控制。安裝、功能、價格、相容性和故障排除。',
    ar: 'الأسئلة الشائعة حول MACA – تحكم في الصوت لكل تطبيق على macOS. الإعداد والميزات والأسعار والتوافق واستكشاف الأخطاء.',
    ru: 'Часто задаваемые вопросы о MACA – управление громкостью приложений на macOS. Установка, функции, цены, совместимость и устранение неполадок.',
    nl: 'Veelgestelde vragen over MACA – volume per app voor macOS. Installatie, functies, prijzen, compatibiliteit en probleemoplossing.',
    tr: 'MACA hakkında sık sorulan sorular – macOS için uygulama başına ses kontrolü. Kurulum, özellikler, fiyatlar, uyumluluk ve sorun giderme.',
    sv: 'Vanliga frågor om MACA – volymkontroll per app för macOS. Installation, funktioner, priser, kompatibilitet och felsökning.',
    da: 'Ofte stillede spørgsmål om MACA – per-app lydstyrkekontrol for macOS. Opsætning, funktioner, priser, kompatibilitet og fejlfinding.',
    ko: 'MACA FAQ – macOS 앱별 볼륨 컨트롤. 설치, 기능, 가격, 호환성 및 문제 해결에 대한 답변.',
    nb: 'Ofte stilte spørsmål om MACA – per-app volumkontroll for macOS. Oppsett, funksjoner, priser, kompatibilitet og feilsøking.',
  },
  guide: {
    en: 'Step-by-step user guide for MACA. Learn how to set up per-app volume control, audio profiles, the 10-band equalizer and Focus Mode on macOS.',
    de: 'Schritt-für-Schritt-Anleitung für MACA. Lautstärke pro App einrichten, Audio-Profile, 10-Band-Equalizer und Fokus-Modus auf macOS nutzen.',
    fr: 'Guide utilisateur étape par étape pour MACA. Configurer le volume par app, profils audio, égaliseur 10 bandes et Mode Focus sur macOS.',
    es: 'Guía de usuario paso a paso para MACA. Configura el volumen por app, perfiles de audio, ecualizador de 10 bandas y Modo Enfoque en macOS.',
    it: 'Guida utente passo passo per MACA. Configura volume per app, profili audio, equalizzatore 10 bande e Modalità Focus su macOS.',
    ja: 'MACAユーザーガイド。アプリ別音量、オーディオプロファイル、10バンドEQ、フォーカスモードの設定方法をステップバイステップで解説。',
    'zh-Hans': 'MACA用户指南。逐步学习如何在macOS上设置每应用音量控制、音频配置文件、10段均衡器和专注模式。',
    'zh-Hant': 'MACA用戶指南。逐步學習如何在macOS上設定每應用音量控制、音頻配置文件、10段均衡器和專注模式。',
    ar: 'دليل المستخدم خطوة بخطوة لـ MACA. تعلم كيفية إعداد التحكم في الصوت لكل تطبيق والملفات الصوتية والمعادل ووضع التركيز على macOS.',
    ru: 'Пошаговое руководство пользователя MACA. Настройка громкости по приложениям, аудиопрофили, 10-полосный эквалайзер и режим фокусировки на macOS.',
    nl: 'Stapsgewijze handleiding voor MACA. Leer per-app volume, audioprofielen, 10-bands EQ en Focusmodus instellen op macOS.',
    tr: 'MACA için adım adım kullanıcı kılavuzu. macOS\'te uygulama bazlı ses kontrolü, ses profilleri, 10 bantlı EQ ve Odak Modunu ayarlamayı öğrenin.',
    sv: 'Steg-för-steg-guide för MACA. Lär dig ställa in volymkontroll per app, ljudprofiler, 10-bands EQ och Fokusläge på macOS.',
    da: 'Trin-for-trin-guide til MACA. Lær at konfigurere per-app lydstyrke, lydprofiler, 10-bands EQ og Fokusmodus på macOS.',
    ko: 'MACA 사용자 가이드. macOS에서 앱별 볼륨, 오디오 프로필, 10대 EQ, 포커스 모드 설정 방법을 단계별로 안내합니다.',
    nb: 'Steg-for-steg-guide for MACA. Lær å sette opp per-app volumkontroll, lydprofiler, 10-bands EQ og Fokusmodus på macOS.',
  },
  troubleshooting: {
    en: 'Troubleshooting MACA – fix common issues with per-app volume control on macOS. Audio permissions, app detection, EQ problems and more.',
    de: 'MACA Fehlerbehebung – häufige Probleme mit Lautstärke pro App auf macOS lösen. Audio-Berechtigungen, App-Erkennung, EQ-Probleme und mehr.',
    fr: 'Dépannage MACA – résoudre les problèmes courants de volume par app sur macOS. Autorisations audio, détection d\'apps, problèmes d\'EQ.',
    es: 'Solución de problemas de MACA – resuelve problemas comunes con el volumen por app en macOS. Permisos de audio, detección de apps, problemas de EQ.',
    it: 'Risoluzione problemi MACA – risolvi problemi comuni con il volume per app su macOS. Permessi audio, rilevamento app, problemi EQ.',
    ja: 'MACAトラブルシューティング – macOSアプリ別音量の一般的な問題を解決。オーディオ権限、アプリ検出、EQ問題など。',
    'zh-Hans': 'MACA故障排除 – 解决macOS每应用音量控制的常见问题。音频权限、应用检测、均衡器问题等。',
    'zh-Hant': 'MACA故障排除 – 解決macOS每應用音量控制的常見問題。音頻權限、應用檢測、均衡器問題等。',
    ar: 'استكشاف أخطاء MACA – حل المشكلات الشائعة في التحكم بالصوت لكل تطبيق على macOS. أذونات الصوت واكتشاف التطبيقات ومشاكل المعادل.',
    ru: 'Устранение неполадок MACA – решение частых проблем с управлением громкостью на macOS. Разрешения аудио, обнаружение приложений, проблемы с EQ.',
    nl: 'MACA probleemoplossing – los veelvoorkomende problemen op met per-app volume op macOS. Audiomachtigingen, app-detectie, EQ-problemen.',
    tr: 'MACA sorun giderme – macOS\'te uygulama bazlı ses kontrolü sorunlarını çözün. Ses izinleri, uygulama algılama, EQ sorunları.',
    sv: 'MACA felsökning – lös vanliga problem med volymkontroll per app på macOS. Ljudbehörigheter, appidentifiering, EQ-problem.',
    da: 'MACA fejlfinding – løs almindelige problemer med per-app lydstyrke på macOS. Lydtilladelser, app-registrering, EQ-problemer.',
    ko: 'MACA 문제 해결 – macOS 앱별 볼륨 컨트롤의 일반적인 문제를 해결하세요. 오디오 권한, 앱 감지, EQ 문제 등.',
    nb: 'MACA feilsøking – løs vanlige problemer med per-app volumkontroll på macOS. Lydtillatelser, app-gjenkjenning, EQ-problemer.',
  },
  privacy: {
    en: 'MACA Privacy Policy – No data collection, no tracking, no analytics. Everything runs locally on your Mac. Your audio data never leaves your device.',
    de: 'MACA Datenschutzerklärung – Keine Datenerhebung, kein Tracking, keine Analyse. Alles läuft lokal auf deinem Mac. Deine Audiodaten verlassen nie dein Gerät.',
    fr: 'Politique de confidentialité MACA – Aucune collecte de données, aucun suivi, aucune analyse. Tout fonctionne localement sur votre Mac.',
    es: 'Política de privacidad de MACA – Sin recopilación de datos, sin seguimiento, sin análisis. Todo funciona localmente en tu Mac.',
    it: 'Informativa sulla privacy MACA – Nessuna raccolta dati, nessun tracciamento, nessuna analisi. Tutto funziona localmente sul tuo Mac.',
    ja: 'MACAプライバシーポリシー – データ収集なし、トラッキングなし、分析なし。すべてMac上でローカル処理。音声データはデバイスから出ません。',
    'zh-Hans': 'MACA隐私政策 – 无数据收集、无追踪、无分析。一切在Mac本地运行。音频数据不会离开设备。',
    'zh-Hant': 'MACA隱私政策 – 無數據收集、無追蹤、無分析。一切在Mac本地運行。音頻數據不會離開設備。',
    ar: 'سياسة خصوصية MACA – بدون جمع بيانات، بدون تتبع، بدون تحليلات. كل شيء يعمل محلياً على جهاز Mac الخاص بك.',
    ru: 'Политика конфиденциальности MACA – Без сбора данных, без отслеживания, без аналитики. Всё работает локально на вашем Mac.',
    nl: 'MACA Privacybeleid – Geen dataverzameling, geen tracking, geen analyse. Alles draait lokaal op je Mac.',
    tr: 'MACA Gizlilik Politikası – Veri toplama yok, izleme yok, analiz yok. Her şey Mac\'inizde yerel olarak çalışır.',
    sv: 'MACA Integritetspolicy – Ingen datainsamling, ingen spårning, ingen analys. Allt körs lokalt på din Mac.',
    da: 'MACA Privatlivspolitik – Ingen dataindsamling, ingen sporing, ingen analyse. Alt kører lokalt på din Mac.',
    ko: 'MACA 개인정보 보호정책 – 데이터 수집 없음, 추적 없음, 분석 없음. 모든 것이 Mac에서 로컬로 처리됩니다.',
    nb: 'MACA Personvern – Ingen datainnsamling, ingen sporing, ingen analyse. Alt kjører lokalt på din Mac.',
  },
  terms: {
    en: 'Terms of Use for MACA – Master Audio Control App for macOS. License terms, usage rights, free vs. Pro version, one-time purchase conditions.',
    de: 'Nutzungsbedingungen für MACA – Master Audio Control App für macOS. Lizenzbedingungen, Nutzungsrechte, Free vs. Pro, Einmalkauf.',
    fr: 'Conditions d\'utilisation de MACA – Master Audio Control pour macOS. Licence, droits d\'utilisation, version gratuite vs. Pro, achat unique.',
    es: 'Términos de uso de MACA – Master Audio Control para macOS. Licencia, derechos de uso, versión gratuita vs. Pro, compra única.',
    it: 'Termini d\'uso di MACA – Master Audio Control per macOS. Licenza, diritti d\'uso, versione gratuita vs. Pro, acquisto unico.',
    ja: 'MACA利用規約 – macOS用Master Audio Control App。ライセンス条件、使用権、無料版 vs. Pro版、買い切り条件。',
    'zh-Hans': 'MACA使用条款 – macOS Master Audio Control App。许可条款、使用权、免费版与Pro版、一次性购买条件。',
    'zh-Hant': 'MACA使用條款 – macOS Master Audio Control App。許可條款、使用權、免費版與Pro版、一次性購買條件。',
    ar: 'شروط استخدام MACA – Master Audio Control لـ macOS. شروط الترخيص وحقوق الاستخدام والنسخة المجانية مقابل Pro والشراء لمرة واحدة.',
    ru: 'Условия использования MACA – Master Audio Control для macOS. Лицензия, права использования, бесплатная vs. Pro версия, разовая покупка.',
    nl: 'Gebruiksvoorwaarden voor MACA – Master Audio Control voor macOS. Licentievoorwaarden, gebruiksrechten, gratis vs. Pro, eenmalige aankoop.',
    tr: 'MACA Kullanım Şartları – macOS için Master Audio Control. Lisans koşulları, kullanım hakları, ücretsiz vs. Pro, tek seferlik satın alma.',
    sv: 'Användarvillkor för MACA – Master Audio Control för macOS. Licensvillkor, användningsrättigheter, gratis vs. Pro, engångsköp.',
    da: 'Brugervilkår for MACA – Master Audio Control for macOS. Licensvilkår, brugsrettigheder, gratis vs. Pro, én gangskøb.',
    ko: 'MACA 이용 약관 – macOS용 Master Audio Control App. 라이선스 조건, 사용권, 무료 vs. Pro 버전, 일회 구매 조건.',
    nb: 'Vilkår for bruk av MACA – Master Audio Control for macOS. Lisensvilkår, bruksrettigheter, gratis vs. Pro, én gangskjøp.',
  },
  imprint: {
    en: 'Imprint & Legal Notice – MACA Master Audio Control. Publisher information, contact details, and legal disclosures for the MACA macOS app.',
    de: 'Impressum – MACA Master Audio Control. Angaben gemäß § 5 TMG, Kontaktdaten und rechtliche Hinweise zur MACA macOS App.',
    fr: 'Mentions légales – MACA Master Audio Control. Informations éditeur, coordonnées et mentions légales pour l\'app MACA macOS.',
    es: 'Aviso legal – MACA Master Audio Control. Información del editor, datos de contacto y avisos legales de la app MACA para macOS.',
    it: 'Note legali – MACA Master Audio Control. Informazioni editore, contatti e informative legali per l\'app MACA macOS.',
    ja: '法的情報 – MACA Master Audio Control。発行者情報、連絡先、MACA macOSアプリの法的開示。',
    'zh-Hans': '法律信息 – MACA Master Audio Control。出版者信息、联系方式和MACA macOS应用的法律声明。',
    'zh-Hant': '法律資訊 – MACA Master Audio Control。出版者資訊、聯絡方式和MACA macOS應用的法律聲明。',
    ar: 'البيان القانوني – MACA Master Audio Control. معلومات الناشر وتفاصيل الاتصال والإفصاحات القانونية لتطبيق MACA لـ macOS.',
    ru: 'Юридическая информация – MACA Master Audio Control. Данные издателя, контактные данные и правовая информация о приложении MACA для macOS.',
    nl: 'Colofon – MACA Master Audio Control. Uitgeversinformatie, contactgegevens en juridische kennisgevingen voor de MACA macOS-app.',
    tr: 'Yasal Bilgiler – MACA Master Audio Control. Yayıncı bilgileri, iletişim bilgileri ve MACA macOS uygulaması için yasal açıklamalar.',
    sv: 'Impressum – MACA Master Audio Control. Utgivarinformation, kontaktuppgifter och juridiska upplysningar för MACA macOS-appen.',
    da: 'Impressum – MACA Master Audio Control. Udgiveroplysninger, kontaktoplysninger og juridiske oplysninger for MACA macOS-appen.',
    ko: '법적 정보 – MACA Master Audio Control. 퍼블리셔 정보, 연락처 및 MACA macOS 앱에 대한 법적 공개.',
    nb: 'Impressum – MACA Master Audio Control. Utgiverinfo, kontaktdetaljer og juridiske opplysninger for MACA macOS-appen.',
  },
  feedback: {
    en: 'Send feedback or report bugs for MACA – Master Audio Control for macOS. Help us improve per-app volume control, EQ, profiles and Focus Mode.',
    de: 'Feedback senden oder Bugs melden für MACA – Master Audio Control für macOS. Helfen Sie uns, Lautstärke pro App, EQ, Profile und Fokus-Modus zu verbessern.',
    fr: 'Envoyez vos commentaires ou signalez des bugs pour MACA – Master Audio Control pour macOS. Aidez-nous à améliorer le volume par app, l\'EQ et le Mode Focus.',
    es: 'Envía comentarios o reporta errores de MACA – Master Audio Control para macOS. Ayúdanos a mejorar el volumen por app, EQ, perfiles y Modo Enfoque.',
    it: 'Invia feedback o segnala bug per MACA – Master Audio Control per macOS. Aiutaci a migliorare volume per app, EQ, profili e Modalità Focus.',
    ja: 'MACAへのフィードバックやバグ報告。macOS用Master Audio Controlのアプリ別音量、EQ、プロファイル、フォーカスモードの改善にご協力ください。',
    'zh-Hans': '为MACA发送反馈或报告错误 – macOS Master Audio Control。帮助我们改进每应用音量、EQ、配置文件和专注模式。',
    'zh-Hant': '為MACA發送回饋或報告錯誤 – macOS Master Audio Control。幫助我們改進每應用音量、EQ、設定檔和專注模式。',
    ar: 'أرسل ملاحظاتك أو أبلغ عن أخطاء في MACA – Master Audio Control لـ macOS. ساعدنا في تحسين التحكم بالصوت والمعادل ووضع التركيز.',
    ru: 'Отправьте отзыв или сообщите об ошибке в MACA – Master Audio Control для macOS. Помогите улучшить управление громкостью, EQ, профили и режим фокусировки.',
    nl: 'Stuur feedback of meld bugs voor MACA – Master Audio Control voor macOS. Help ons volume per app, EQ, profielen en Focusmodus te verbeteren.',
    tr: 'MACA için geri bildirim gönderin veya hata bildirin – macOS için Master Audio Control. Uygulama sesi, EQ, profiller ve Odak Modunu iyileştirmemize yardımcı olun.',
    sv: 'Skicka feedback eller rapportera buggar för MACA – Master Audio Control för macOS. Hjälp oss förbättra volym per app, EQ, profiler och Fokusläge.',
    da: 'Send feedback eller rapportér fejl for MACA – Master Audio Control for macOS. Hjælp os med at forbedre lydstyrke per app, EQ, profiler og Fokusmodus.',
    ko: 'MACA에 피드백을 보내거나 버그를 신고하세요 – macOS용 Master Audio Control. 앱별 볼륨, EQ, 프로필 및 포커스 모드 개선에 도움을 주세요.',
    nb: 'Send tilbakemelding eller rapporter feil for MACA – Master Audio Control for macOS. Hjelp oss å forbedre volum per app, EQ, profiler og Fokusmodus.',
  },
};

function getPathParts(pathname: string) {
  return pathname.split('/').filter(Boolean);
}

export function getRouteSeo(pathname: string) {
  const pathParts = getPathParts(pathname);
  const lang = resolveLanguage(pathParts[0]);
  const slugCandidate = pathParts[1];
  const pageKey: SeoPageKey = SEO_PAGE_SLUGS.includes(slugCandidate as SeoPageKey)
    ? (slugCandidate as SeoPageKey)
    : 'home';
  const normalizedPath = pathname.replace(/\/+$/, '') || '/';
  const canonicalPath = normalizedPath === '/' ? `/${DEFAULT_LANGUAGE}` : normalizedPath;

  return {
    lang,
    pageKey,
    title: PAGE_TITLES[pageKey][lang] || PAGE_TITLES[pageKey][DEFAULT_LANGUAGE],
    description: META_DESCRIPTIONS[pageKey][lang] || META_DESCRIPTIONS[pageKey][DEFAULT_LANGUAGE],
    canonicalPath,
    canonicalUrl: `${BASE_URL}${canonicalPath}`,
    direction: isRtl(lang) ? 'rtl' : 'ltr',
    ogLocale: OG_LOCALE_MAP[lang],
    robots: pageKey === 'feedback'
      ? 'noindex, nofollow'
      : 'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1',
  };
}

export function getAlternateLinks(pathname: string) {
  const { pageKey } = getRouteSeo(pathname);
  const pageSuffix = pageKey === 'home' ? '' : `/${pageKey}`;

  return SUPPORTED_LANGUAGES.map((lang) => ({
    lang,
    href: `${BASE_URL}/${lang}${pageSuffix}`,
  }));
}